### PR TITLE
Improve test discoverability

### PR DESCRIPTION
**Pull request by Xiretza**
I came across some problems when trying to package this for the AUR, these patches should fix those without affecting anything else.

### CODE REVIEW

**Comment by umarcor** [comment]
@Xiretza, while adding `__init__.py` might be ok, having an `*.ini` file and not naming test files `test_*` is a design decision from Patrick. Is there any chance of making it work in AUR without modifying the file name?

**Comment by Xiretza** [comment]
Apparently `pytest` reads the `pytest.ini` in directories explicitly passed on the commandline, so while not ideal, `pytest tests/` works.

**Comment by umarcor** [comment]
Nice and thanks! LGTM. However, I'll let @Paebbels merge.

**Comment by Paebbels** [comment]
@Xiretza I merged it. Thanks.

Do you need this package as a released version on PyPI or is the modified source ok (via this merge)?
The (full) release pipeline runs only on tags.

**Comment by Xiretza** [comment]
No, Arch packages are built directly from the sources (either release tarballs or, as in this case, the HEAD of the git repo), not pypi releases. Thanks for the merge!

**Pull request merged**
