### PR TITLE
Adding resolution of record element subtypes in packages

### PR DESCRIPTION
**Pull request by Tcenova**
# New Features
 
* Record element subtypes are now resolved in packages

### CODE REVIEW

**Review by Paebbels — APPROVED** [review]
LGTM.

**Comment by Paebbels** [comment]
@Tcenova do you need this change to be released as v0.29.0 or is a merge to `dev` branch ok so far?

Currently, `dev` branch has only a few changes.

**Comment by Tcenova** [comment]
The `dev` branch is fine for now. I am waiting on your changes in the `standalone` branch of ghdl to make there way to master before it would be useful. I have been testing with a combination of branches of things to get type resolution working. Its also possible I may have other pull requests in the future if I implement other missing pieces.

**Comment by Paebbels** [comment]
>  I am waiting on your changes in the standalone branch of ghdl to make there way to master before it would be useful.

Are you waiting because of the standalone installation feature or because of gathered additions to GHDL?

**Comment by Paebbels** [comment]
May I asked if the pyVHDLModel is so far understandable. It doesn't have lots of documentation and it might not be easy to understand what I did and how I did it :).

**Comment by Tcenova** [comment]
> > I am waiting on your changes in the standalone branch of ghdl to make there way to master before it would be useful.
> 
> Are you waiting because of the standalone installation feature or because of gathered additions to GHDL?

I am mainly waiting on the changes to pyGHDL that allow it to use the latest version of pyVHDLModel. Overall, I am trying to fully parse an entities ports and generics.  I have some local code to also resolve subtypes of the ports which is only possible with the latest code. I am also trying to extract the constraints of ports and generics on an entity, hence why I opened ghdl/ghdl#2661

> May I asked if the pyVHDLModel is so far understandable. It doesn't have lots of documentation and it might not be easy to understand what I did and how I did it :).

I cant say I have been able to understand the high level approach/reasoning for things yet, but I also haven't spent much time trying. There seems to be many layers, along with more layers added in the DOM in pyGHDL, so traversing through the layers has sometimes been a challenge. I am able to generally understand how to use things after looking at the different layers of source code though.

**Comment by Paebbels** [comment]
Oh, https://github.com/ghdl/ghdl/issues/2661. I didn't recognize your name from there. Sorry.

I'll try to invest more time into it.

**Pull request merged**
